### ISSUE TITLE
error when building with g++ 6.1

### ISSUE THREAD

**Issue by tillea** [mateidavid/hpptools#3]
Hi,

as you know I intend to create a Debian package moving the header files to /usr/include/hpptools.  When trying the examples with gcc version 6.1 I get:

$ g++ -std=c++11 -O0 -g3 -ggdb -fno-eliminate-unused-debug-types -Wall -Wextra -pedantic -I/usr/include/hpptools -o test-alg test-alg.cpp -lz
In file included from test-alg.cpp:9:0:
/usr/include/hpptools/alg.hpp:570:12: error: ‘std::accumulate’ has not been declared
 using std::accumulate;
            ^~~~~~~~~~

BTW, this is after I fixed another error in alg.hpp

$ g++ -std=c++11 -O0 -g3 -ggdb -fno-eliminate-unused-debug-types -Wall -Wextra -pedantic -D SAMPLE_ALG -x c++ alg.hpp -o sample-alg
alg.hpp: In function ‘std::pair<_FIter, _FIter> alg::mean_stdv_of(Input_Iterator, Input_Iterator, Unary_Function&&)’:
alg.hpp:477:30: error: ‘sqrt’ is not a member of ‘std’
     Float_Type stdv = n > 1? std::sqrt((s2 - s * mean * 2.0 + mean * mean * (Float_Type)n)/(n - 1)) : (Float_Type)0;
                              ^~~

which I was able to fix myself by simply including
``#include <math.h>``

Unfortunately I was not able to fix the above error due to very low C++ knowledge.

Kind regards

        Andreas.

**Comment by tillea** [comment]
Additional hint:  The latest state in Git does not need math.h include.  I was refering to the release tag 1.1.0 when writing above.  However the ‘std::accumulate’ issue exists also in latest Git commit.

**Comment by mateidavid** [comment]
Let's forget about old tags and work on HEAD of master. I'll tag a release when this works.

I am surprised by the error message, because `std::accumulate` should be in `numeric`, which is already included.

I just added the possibility to run the tests under Docker, in order to allow for using other GCC versions.

Here's what I'm trying, and I don't see any errors:
```
cd examples
make -f test-alg.make test DOCKER_CMD="docker run --rm -i -e TZ=$(cat /etc/timezone) -u $(id -u):$(id -g) -v $PWD/..:/data -w /data/examples -v /usr/include/boost:/usr/include/boost gcc:6.1.0"
```

This compiles and runs the tests with:
```
$ docker run --rm gcc:6.1.0 g++ --version
g++ (GCC) 6.1.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I tried 6.1.0, 5.3.0, and 5.2.0 this way, and they all work with no errors. Can you make sure you're using master HEAD and 6.1.0?

**Comment by mateidavid** [comment]
I pushed a new tag, 1.1.1, let's work on this one.

**Comment by tillea** [comment]
On Wed, Sep 14, 2016 at 12:47:36PM -0700, Matei David wrote:
> I pushed a new tag, 1.1.1, let's work on this one.

This works with the tests and nanocall as well.  Thanks for the fix.

The only real blocker for nanocall build is now fast5 issue #11.

Thanks for your very helpful support

      Andreas.

-- 
http://fam-tille.de
